---

- name: Deploy Frontend
  hosts:
  - tag_Name_dumbledore
  user: ubuntu
  sudo: true
  gather_facts: true
  tasks:
      - name: Copy project Dist
        copy: src=../target/dumbledore-dist dest=/usr/local/

      - name: Run Frontend Akka
        command: nohup /usr/local/dumbledore-dist/bin/start com.winston.boot.DumbledoreBoot &
