---

- name: Deploy
  hosts:
  - tag_Name_dumbledore-frontend-01
  user: ubuntu
  sudo: true
  gather_facts: true
  tasks:
      - name: Copy project Dist
        copy: src=../target/dumbledore-dist dest=/usr/local/

      - name: Run Akka
        command: /usr/local/dumbledore-dist/bin/start com.winston.boot.DumbledoreBoot
