---

- name: Re-deploy Single
  hosts:
  - tag_Name_dumbledore
  user: ubuntu
  sudo: true
  gather_facts: false
  tasks:
      - name: Kill previous run
        command: killall java
        ignore_errors: yes

      - name: Copy project Dist
        copy: src=../target/dumbledore-dist dest=/usr/local/

      - name: Run Frontend
        command: nohup /usr/local/dumbledore-dist/bin/start com.winston.boot.DumbledoreBoot &
        async: 450000
        poll: 0